#!/bin/bash

ORIG_PWD=$(pwd)
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done

cd "$( cd -P "$( dirname "$SOURCE" )" && pwd )"

docker run --rm \
	-v "$(pwd)/conf":/flyway/conf \
	-v "$(pwd)/sql":/flyway/sql \
	boxfuse/flyway:5.0.7-alpine \
	$*